### ISSUE TITLE
The performance of NeuralSparseGCN

### ISSUE THREAD

**Issue by hhr114** [flyingdoog/PTDNet#1]
Hi,
Thx for your work. I have run NeuralSparse/train.py, which is NeuralSparseGCN as far as I can know. 
However, the performance of NeuralSparseGCN is worse than what is reported. 
Could you help me?

**Comment by flyingdoog** [comment]
Hi,

Since this is the unofficial implementation,  I tried to follow the description in the original paper but found that with their settings, it is hard to get the reported results.  There are might be some missing tricks or details. Or hyper-parameters tunning are needed.  I am not a co-author of that paper, you may ask the authors for these information.
